// import linkedList from './linked-list'
// import shellsort from './sort/shellsort'
// import quicksort from './sort/quicksort'
// import Stack from './stacks'
// import Queue from './queues'
import bintree from './binary-trees'